name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'  # Use Java 23
          distribution: 'temurin'

      # Install Chrome and ChromeDriver
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      # Build and run tests
      - name: Build and run tests
        run: mvn clean test  # For Maven
        # run: ./gradlew clean test  # For Gradle

      # Generate and publish reports
      - name: Publish Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-reports  # Path to the Cucumber HTML report
          if-no-files-found: error

      - name: Publish Allure Report
        if: always()  # Always run this step, even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-results  # Path to the Allure results
          if-no-files-found: error

      - name: Publish ExtentReports
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: target/extent-reports  # Path to the ExtentReports
          if-no-files-found: error