name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      # Set up Chrome using a preconfigured action
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      # Debug Environment
      - name: Debug Environment
        run: |
          echo "Java version:"
          java -version
          echo "Maven version:"
          mvn -version
          echo "Chrome version:"
          google-chrome --version
          echo "ChromeDriver version:"
          chromedriver --version

      # Build and run tests
      - name: Build and run tests
        run: mvn clean test  # For Maven
        # run: ./gradlew clean test  # For Gradle

      # List report directories for debugging
      - name: List Report Directories
        run: |
          ls -R target/cucumber-reports
          ls -R allure-results
          ls -R target/extent-reports

      # Generate and publish reports
      - name: Publish Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-reports
          if-no-files-found: error

      - name: Publish Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-results
          if-no-files-found: error

      - name: Publish ExtentReports
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: target/extent-reports
          if-no-files-found: error
